#!/bin/bash
# Generate sitemap.xml with current date

SITEMAP_PATH="public/sitemap.xml"
CURRENT_DATE=$(date +%Y-%m-%d)

cat > "$SITEMAP_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file is auto-generated by scripts/generate-sitemap.sh
  The lastmod date is dynamically set to the current date when the script runs.
  Run ./scripts/generate-sitemap.sh before committing to update the date.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://math-game.oceanofmaya.com/</loc>
    <lastmod>${CURRENT_DATE}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
EOF

echo "Generated sitemap.xml with lastmod date: ${CURRENT_DATE}"

